### ISSUE TITLE
Merging with original Cake.NSwag addin

### ISSUE THREAD

**Issue by gep13** [lukoerfer/cake-codegen-nswag#1]
@lukoerfer My name is Gary, and I am one of the Cake Team Members.  I wanted to reach out to you regarding your new Cake.CodeGen.NSwag Addin:

https://www.nuget.org/packages/Cake.CodeGen.NSwag/

You mention in your readme that you were aware of the existing Cake.NSwag addin, and I wanted to see if you thought that it would make sense to combine efforts, rather than have two competing addins.

I have just spoken with the original addin created, and I have moved the Cake.NSwag Repository under the Cake-Contrib Organisation on GitHub:

https://github.com/cake-contrib/Cake.NSwag

**NOTE:** For more information on with this Organisation is, there is a [blog post](https://cakebuild.net/blog/2016/08/cake-contribution-organization) that you can read.

Would you be interested in being added to this repository as an admin, to continue the work that you are doing there?

Personally, I think that this would make a lot of sense, as it would prevent any confusion about what is the correct addin to use when using NSwag with Cake.

It would be great if you can let me know your thoughts on this, and if you have any questions, please feel free to reach out, I would be happy to jump on a Skype/Zoom call to discuss further.

**Comment by lukoerfer** [comment]
@gep13 Hi Gary, of course I think that a single addin would make sense to both combine efforts and to prevent confusion for other users of Cake, so of course we can merge them. When I found the original addin, I tried to apply it but failed. Since the last update on the repo was from two years ago and even "simple" issues by the guideline bot were unanswered, I expected the project to be dead, so I started the new addin instead of just raising an issue / pull-request there.

However, right now I'm a little bit busy with regular work (for which I kinda developed this addin) and upcoming exams, so I could not guarantee any times or schedules for when to work on merging the addins. This is also the reason, why things like a proper documentation and testing are still missing from the project, which is something I should definitively work on. But we needed the addin at work and since our local NuGet feeds are only for internal packages (and I kinda like OSS), I published globally.

Regarding the process of merging the addins, how would you approach it?
Should the addin API still be the one from the old addin or should the new addin just be published as a (breaking) new version of the old addin?
Of course, we can also work on these details via Skype as you suggested, feel free to contact me via mail to agree on a date and time. You can find the mail address at my public (outdated) website, which is linked on my user profile.

**Comment by gep13** [comment]
@lukoerfer please accept my apologies!  I meant to get back to you sooner about this, but completely forgot about it.

The original Cake.NSwag repository has now been moved into the Cake-Contrib Organisation:

https://github.com/cake-contrib/Cake.NSwag

Which would mean that more than one person would be able to work on it, and we can avoid duplication of effort.

I am going to go ahead and invite you to join the Organisation, with permissions for this repository.  From there, you should be able to bring in some of the changes that you have made in this repository.  Does that sound ok?

**Comment by gep13** [comment]
@lukoerfer I will go ahead and close out this issue.  Let me know if you have any problems with contributing to the NSwag repository now that it has been moved to the Cake Contrib Organisation.

It would be good to get you added to the Cake Contrib Slack Team where you can ask any questions you might have as well.  If you can let me know the best email address to use, I can send you an invite.  Also, if you could let me know if you are on Twitter, that would be great too.
